services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tombola
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  indexer:
    container_name: indexer
    build:
      context: ../
      dockerfile: ./docker/indexer/Dockerfile
    image: indexer
    volumes:
      - config-data:/data
    restart: always
    depends_on:
      - postgres
      - redis

  graphql:
    container_name: graphql
    build:
      context: ../
      dockerfile: ./docker/graphql/Dockerfile
    image: graphql
    ports:
      - 8001:8001
    volumes:
      - config-data:/data
    restart: always
    depends_on:
      - postgres
      - redis
      
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus-data
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=expand-external-labels'
    depends_on:
      - otlp-collector

  tempo:
    container_name: grafana-tempo
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./grafana/tempo.yml:/etc/tempo.yml
      - ./grafana/tempo-data:/tmp/tempo
    ports:
       - "3200:3200"    # tempo
       - "9095:9095"    # tempo grpc
       # - "4317:4317"    # otlp grpc
       # - "4318:4318"    # otlp http

  loki:
    container_name: grafana-loki
    image: grafana/loki:main
    restart: always
    volumes:
      - ./grafana/loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "33000:3000"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana-data:/grafana
    env_file:
      - ./grafana/.env.grafana
    restart: always
  
  grafana-nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/grafana.crt:/etc/nginx/ssl/self.cert
      - ./nginx/grafana.key:/etc/nginx/ssl/self-ssl.key
    depends_on:
      - grafana

  otlp-collector:
    container_name: otlp-collector
    image: otel/opentelemetry-collector-contrib:0.119.0
    command: "--config /etc/otel-config.yaml"
    volumes:
      - ./opentelemetry/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317" # gRPC OTLP receiver
      - "4318:4318" # HTTP OTLP receiver
      - "8889:8889" # Prometheus
    depends_on:
      - tempo
      - loki

  tests:
    container_name: tests
    build:
      context: ../
      dockerfile: ./docker/tests/Dockerfile
    image: tests
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRESQL_URL=postgresql://postgres:postgres@postgres:5432/tombola
    volumes:
      - config-data:/data
    depends_on:
      - postgres
      - redis

volumes:
  config-data:
    driver: local
  contracts-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  postgres-data:
    driver: local
